ahoyapi: v1
version: 0.0.0
commands:
  install:
    cmd: "go install"
    usage: Build ahoy using go install.
  test:
    cmd: "go test"
    usage: Test out ahoy using go.
  docker:
    #cmd: "ahoy help home"
    usage: Example docker commands from examples/docker.ahoy.yml
    import: examples/docker.ahoy.yml
  confirm:
    cmd: "ahoy -f examples/confirmation.ahoy.yml confirm {{args}}"
    usage: Example of importing a single docker command from examples/confirmation.ahoy.yml
    hide: true
  init:
    cmd: echo ".ahoy.yml file already exists."
    hide: true
